### ISSUE TITLE
ローカル開発環境を構築する

### ISSUE THREAD

**Issue by k2works** [parkmap-h/parkmap#1]
- [x] README.mdを作る
- [x] [PostGISをローカルでセットアップする](http://blog.eiel.info/blog/2014/12/11/postgis-abc/)
- [ ] ~~VagrantFileを用意する~~
- [ ] ~~cookbookレシピを用意する~~

**Comment by s-rem** [comment]
VargrantFileとcookbookもねw

**Comment by k2works** [comment]
```bash
 $ rake db:create
rake aborted!
NameError: uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQLAdapter::TableDefinition
/Users/k2works/.rvm/gems/ruby-2.1.5@parkmap/gems/activerecord-postgis-adapter-2.2.0/lib/active_record/connection_adapters/postgis_adapter/spatial_table_definition.rb:4:in `<module:PostGISAdapter>'
/Users/k2works/.rvm/gems/ruby-2.1.5@parkmap/gems/activerecord-postgis-adapter-2.2.0/lib/active_record/connection_adapters/postgis_adapter/spatial_table_definition.rb:3:in `<module:ConnectionAdapters>'
/Users/k2works/.rvm/gems/ruby-2.1.5@parkmap/gems/activerecord-postgis-adapter-2.2.0/lib/active_record/connection_adapters/postgis_adapter/spatial_table_definition.rb:2:in `<module:ActiveRecord>'
/Users/k2works/.rvm/gems/ruby-2.1.5@parkmap/gems/activerecord-postgis-adapter-2.2.0/lib/active_record/connection_adapters/postgis_adapter/spatial_table_definition.rb:1:in `<top (required)>'
/Users/k2works/.rvm/gems/ruby-2.1.5@parkmap/gems/activerecord-postgis-adapter-2.2.0/lib/active_record/connection_adapters/postgis_adapter.rb:23:in `<top (required)>'
/Users/k2works/.rvm/gems/ruby-2.1.5@parkmap/gems/activerecord-postgis-adapter-2.2.0/lib/activerecord-postgis-adapter.rb:1:in `require'
/Users/k2works/.rvm/gems/ruby-2.1.5@parkmap/gems/activerecord-postgis-adapter-2.2.0/lib/activerecord-postgis-adapter.rb:1:in `<top (required)>'
/Users/k2works/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.7/lib/bundler/runtime.rb:76:in `require'
/Users/k2works/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.7/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Users/k2works/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.7/lib/bundler/runtime.rb:72:in `each'
/Users/k2works/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.7/lib/bundler/runtime.rb:72:in `block in require'
/Users/k2works/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.7/lib/bundler/runtime.rb:61:in `each'
/Users/k2works/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.7/lib/bundler/runtime.rb:61:in `require'
/Users/k2works/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.7/lib/bundler.rb:133:in `require'
/Users/k2works/Github/parkmap/config/application.rb:36:in `<top (required)>'
/Users/k2works/Github/parkmap/Rakefile:4:in `require'
/Users/k2works/Github/parkmap/Rakefile:4:in `<top (required)>'
/Users/k2works/.rvm/gems/ruby-2.1.5@parkmap/bin/ruby_executable_hooks:15:in `eval'
/Users/k2works/.rvm/gems/ruby-2.1.5@parkmap/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by eiel** [comment]
rails 環境とpostgisをいれるレシピはあるんだけど合わせると動いてくれないせつない子が一応いるんですよね…。

**Comment by eiel** [comment]
4.2へのアップグレードはおいときますかね。

**Comment by s-rem** [comment]
4.1でIaCできるなら、とりあえずは4.1にしときましょう

**Comment by k2works** [comment]
ラジャ

**Comment by eiel** [comment]
調べたらpostgisのadapterが4.2への対応作業中だったら。IaCってなんだろう。

**Comment by s-rem** [comment]
IaC = Infrastructure as Code

**Comment by k2works** [comment]
今週中にはやりますんでちょっと待って下さいね

**Comment by eiel** [comment]
Dockerでの開発環境が1,2時間でつくれてしまった罠。 #6

**Comment by k2works** [comment]
[WIP]Dockerサポートがうまくいかないでござる
2b6ae3566c0c6ea15278bcfbc2516e7fae0a3176

```bash
$ bin/docker_support db
docker run -d --name parkmap-db mdillon/postgis:9.4
FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host? 
$ docker -d
2015/01/28 10:08:18 This is a client-only binary - running the Docker daemon is not supported.
```

Macのクライアントではデーモンをサポートしていないと出ているんですが
デーモンの起動方法どうやるんですか？

**Comment by eiel** [comment]
```
boot2docker up 
```

でデーモンが起動しやす。
その後に以下も実行するとよい。

```
$(boot2docker shellinit)
```


出力が違うので以下のコマンドの結果もほしす。
```
docker -v
boot2docker -v
```
こちら1.4.1なり。

**Comment by eiel** [comment]
docker版はfigを導入するかもしれない。

**Comment by k2works** [comment]
確認できました。
13a2eaf0e2ff03c61832a1b658dbf26dbc199315

ちなみに
```
$ docker -v
Docker version 1.4.1, build 5bc2ff8
$ boot2docker -v
Boot2Docker-cli version: v1.4.1
Git commit: 43241cb
```
なり

あと、`boot2docker up`を実行すると起動中に`docker@localhost's password: `が表示されるんですがあれはバグですか？それとfigって何？

**Comment by s-rem** [comment]
> あと、boot2docker upを実行すると起動中にdocker@localhost's password:が表示されるんですがあれはバグですか？
たしか、実行するユーザをdockerグループに入れとかなきゃいけないんじゃなかったっけ?

> それとfigって何？
同じ疑問を持ったのでググりました。
http://dev.classmethod.jp/server-side/docker-server-side/orchestration-with-boot2docker-fig/
だそうです

**Comment by eiel** [comment]
> あと、boot2docker upを実行すると起動中にdocker@localhost's password:が表示されるんですがあれはバグですか？それとfigって何？

うちはでないなー。

fig はぼくも今朝開発で使えることをおしえてもらったのであった。

http://qiita.com/eielh/items/754c1f785e66e3c4cee0#comment-ca2bab7980cecd02471d

**Comment by k2works** [comment]
figぱないっすね。
6ee56ed79dfd5561660ca4e80eeef6ffffa6dc7c

> あと、boot2docker upを実行すると起動中にdocker@localhost's password:が表示されるんですがあれはバグですか？

```bash
boot2docker delete
rm -rf ~/.boot2docker/ ~/.ssh/id_boot2docker*
boot2docker init
boot2docker up
```
で直りました。
https://github.com/boot2docker/boot2docker/issues/405

VagrantFileもDockerとの比較検証も兼ねてやってみるとします。

**Comment by k2works** [comment]
インフラ開発環境を別途セットアップしました
https://github.com/parkmap-h/parkmap-cookbook-ops
とりあえずカスタムレシピの開発していい感じなったら開発のVagrantFileで呼び出せるようにします。

**Comment by eiel** [comment]
chef-repo形式より単体のcookbook形式にしたいかもしれない。

**Comment by k2works** [comment]
こんなかんじですかね？

https://github.com/parkmap-h/parkmap-cookbook

**Comment by eiel** [comment]
そんな感じっすね。何で生成したんだろう。chef development kitのchefコマンドではなさそうなことぐらいしかわからない

**Comment by eiel** [comment]
しかし、parkmap-cookbook という名前のクックブックになっておられる

**Comment by k2works** [comment]
```
$ knife cookbook create -o site-cookbooks parkmap-cookbook
$ cd site-cookbooks/parkmap-cookbook
$ git init
```
してリモートリポジトリにプッシュしました。
ネーミングはどういうのがいいですかね〜
ちなみに自社ではops（インフラ）dev（開発）をポストフィックスして区分けしているぐらい。

**Comment by eiel** [comment]
parkmap でいいんじゃないっすかねー。
cookbookつくるときはChef コマンドからジェネレートするとtest-kitchenの設定とかberksの設定とかついてきていいっすよ。

**Comment by k2works** [comment]
名前をparkmapにするとレポジトリ名がかぶりませんか？

**Comment by eiel** [comment]
リポジトリ名は接尾辞にcookbookをつけてるマン。

**Comment by k2works** [comment]
クックブック名をparkmapに変更してchefspecできるようにしたマン。
https://github.com/parkmap-h/parkmap-ops

**Comment by eiel** [comment]
(そういえばDockerで運用してるから開発環境ができれば、それで十分なのだけどどこまでやるんだろう…)

**Comment by s-rem** [comment]
(つーかどのみち実運用はMacOS上じゃないから、Vargrant以前とDocker以降を分けてほしいな...)

**Comment by k2works** [comment]
了解、ローカル環境は
https://github.com/parkmap-h/parkmap/pull/35
でクローズとします。
クックブックの開発はぼちぼち継続します(ポスグレをもう少し理解したいのもあるんで）

**Comment by eiel** [comment]
どうせボランティアなのでしたいことをしよう。READMEあざっす。
