### ISSUE TITLE
料金情報のチェック処理をいれる

### ISSUE THREAD

**Issue by eiel** [parkmap-h/parkmap#125]
料金情報を登録する時に正しく料金が計算できない時間がないかチェックする仕組みが欲しい。

**Comment by k2works** [comment]
チェック処理の実装部分はどこ？

**Comment by eiel** [comment]
https://github.com/parkmap-h/parkmap/commit/20665980bb06c42a353da94b70b1e8415b7ac55e

**Comment by k2works** [comment]
サンクス
