### ISSUE TITLE
写真アップロードが出来ない

### ISSUE THREAD

**Issue by k2works** [parkmap-h/parkmap#146]
iPhoneで撮影した写真をPCからアップロードした所以下の画面が表示された。
![2015-05-05 12 19 55](https://cloud.githubusercontent.com/assets/3236312/7466652/4964700e-f322-11e4-95e6-47bb3c2c174a.png)

**Comment by eiel** [comment]
iPhoneで とってても位置情報がついてないことは当然あるけど、文章の問題かしら

**Comment by k2works** [comment]
![2015-05-12 10 20 23](https://cloud.githubusercontent.com/assets/3236312/7578500/d62f70ba-f890-11e4-998f-833926fba19b.png)

写真を書き出す際のオプションで位置情報にチェックを入れたらうまくできた。
