### ISSUE TITLE
料金計算プロトタイプ

### ISSUE THREAD

**Issue by s-rem** [parkmap-h/parkmap#2]
ポスグレのストアドファンクションで単純な計算パターンを実装してみる
・とりあえず 08:00ｰ20:00 100円/20min 20:00-08:00 100円/60分

**Comment by s-rem** [comment]
-[] まずはポスグレ環境構築 inc(Vagrantfile+Chef)
-[] ストアドファンクションの仕様を調べて実験

**Comment by s-rem** [comment]
ポスグレのストアドファンクション、Perlで書けるらしい
ハードル一気に下がったw

**Comment by s-rem** [comment]
vargrant+Chefではなく、Dockerで作成

**Comment by s-rem** [comment]
メモ
**計算式の格納**
駐車場Tableとは別のTableに格納

項目名 | 説明
------- | ----
ProcID | 計算式主キー (AI)
Name | 計算式名称
Argc | 変数の数
Arg | 変数名配列(JSON)
RegTmpl | 駐車場登録時に表示するWebFormのテンプレート
Proc | 計算式(ストアドファンクション) 2+Argc個の引数を持つ 最初の2個は、駐車時刻開始と終了

RegTmplのイメージ (Argが[daystart,dayend,daypay,dayunit,nightstart,nightend,nightpay,nightunitの8つ)
> <%daystart%> ～ <%dayend%> ： <%daypay%>円/<%dayunit%>分&lt;br/>
> <%nightstart%> ～ <%nightend%> ： <%nightpay%>円/<%nightunit%>分

**計算式登録ユースケース**

とりあえずはWebIFなくていいんじゃね?

**駐車場と計算式の関係付け**

駐車場Tableに、下記項目を追加
(あるいは、関係付けTableを作成)

項目名 | 説明
---- | -----
ProcID | 計算式主キー(FK)
Param | パラメータハッシュ( キー:変数名 値:パラメータ値 ) (JSON)

**駐車場への計算式登録ユースケース**

1. -> 変数の数を指定
1. <- 変数の数が一致する計算式のWebFormテンプレート一覧を表示
1. -> 使用する計算式を指定
1. <- WebFormテンプレートから、パラメータ値登録画面を生成して表示
1. -> パラメータ値を入力して登録
1. <- 登録完了

**Comment by eiel** [comment]
ロジックをデータベースに埋め込むのってよくやるんだろうか。

**Comment by s-rem** [comment]
> ロジックをデータベースに埋め込むのってよくやるんだろうか。
口頭では答えたけど、記録のため。
急いで書いたので変な書き方になっただけ。実際にはストアドファンクション名を埋め込むです

というふうに直しときます
