### ISSUE TITLE
Issue管理ツールを試す

### ISSUE THREAD

**Issue by k2works** [parkmap-h/parkmap#27]
[HubBoard](https://huboard.com/parkmap-h/parkmap)
マイルストンごとのかんばんビューもあるので中長期的な進捗の把握ができる。
自社で使っている。

[Waffle](https://waffle.io/)
シンプルに状況を確認できるがマイルストンごとに把握が難しいので中長期的な進捗の把握が難しい。
すごい広島で使っている。

[ZenHub](https://www.zenhub.io/)
chrome エクステンションをつかってGitHubの画面自体を拡張できる。
Github内でお手軽にカンバンが使える。
個人利用ならパブリック・プライベート無料でもチームは有料。

http://qiita.com/GeckoTang/items/f75b9a1c20c8e5091147

[Trello](https://trello.com/b/xhZks1lL/-)
非技術者にも使いやすい。
プロジェクトのステークホルダー向けに長期的な進捗を説明できる。

**Comment by k2works** [comment]
タスクとフィーチャばかりだったのでストーリーを追加してマイルストンをストーリー区切りにしてみた

**Comment by eiel** [comment]
わーい。なんか自動でタスクが生理されてゆくよー。さんくす。

**Comment by k2works** [comment]
とりあえず,HubBoardとTrelloの二本立てでIssueとMilestoneの管理をやってみる。
