### ISSUE TITLE
Macに特化しないようReadme修正

### ISSUE THREAD

**Issue by s-rem** [parkmap-h/parkmap#36]

**Comment by k2works** [comment]
Windows周りの検証ができたらありがたいです。

**Comment by eiel** [comment]
windowsは諦めて仮想環境もしくはどっかーいいかと。

**Comment by s-rem** [comment]
Windowsの場合はVargrantでCentOSなりUbutuなり動かしてDockerがベストかと

**Comment by s-rem** [comment]
コメント記入中にFFが落ちた(TT) 気分も落ちたので、簡潔に

git pullして、ブランチ切って、README書きなおして、動作確認しようとしたらいくつ
か問題が

### fig upでエラー

gemが見つからないと言っているので、該当のものをGemfiles.Lockから削除し、成功

### ダミーデータ投入でエラー
```
$ zcat coinpark.20150203.sql.gz|fig run bin/rails dbconsole
```
すると、「bin/rails というサービスはない」とおっしゃいます。なんか間違ってる?

念のため、fig buildして再度やってみましたが、現象変わらず。  
もしかしたら先にfig buildしたら最初のfig upのエラーは起こらなかったのか?

### ゴミコンテナが残る?
これは以前から気がついていたのだけれど、
```
$ fig run web bin/rake db:setup
```
すると、終了したコンテナ parkmap_web_run_1 が残ります  
(ダミーデータ投入成功した時はもうひとつ残っていた)

とりあえず現状でブランチ issue-36/ReadmeUpdate にpushしておきます。
(Gemfiles.Lockの差分はそっち見てもらえれば)


・・・README直すだけのつもりがえらい時間食ってしまった・・・

**Comment by eiel** [comment]
> gemが見つからないと言っているので、該当のものをGemfiles.Lockから削除し、成功

Gemfile.lockをもどしてfig build してみてください

> ` zcat coinpark.20150203.sql.gz|fig run bin/rails dbconsole`

` zcat coinpark.20150203.sql.gz|fig run web bin/rails dbconsole`

じゃないかなぁ。

**Comment by s-rem** [comment]
Gemfile.lockを戻して再度fig buildしてみます。

ダミーデータ投入は、記憶モレだな。やっぱ理解せずにまる覚えじゃ間違えるわ・・・

**Comment by eiel** [comment]
> すると、終了したコンテナ parkmap_web_run_1 が残ります

これはべつに問題ない気もするけどさてどうなんかなぁ。 --rm オプションとか設定できるんかな。

**Comment by s-rem** [comment]
> これはべつに問題ない気もするけどさてどうなんかなぁ。 --rm オプションとか設定できるんかな。

実害ないのはわかってるんだけど。buildのlog見てると消してるっぽいから出来るなら気持ちが良いかなw

**Comment by s-rem** [comment]
> >  これはべつに問題ない気もするけどさてどうなんかなぁ。 --rm オプションとか設定できるんかな。

> 実害ないのはわかってるんだけど。buildのlog見てると消してるっぽいから出来るなら気持ちが良いかなw

思い出した。yum rm してもコンテナ残ってたから気になったんでした。

**Comment by s-rem** [comment]
で、Gemfile.lock戻して再度やってみたらうまく行ったので、改めてpushしてプルリク出します。
実際masterと変わったのは、README.mdと.gitignore だけ。
