### ISSUE TITLE
データベースにログインする情報がわからない

### ISSUE THREAD

**Issue by k2works** [parkmap-h/parkmap#50]
`bin/rails dbconsole`
ではローカルのDBにアクセスできるけどその時のユーザー名とパスワードが分からない。
config/database.yml見たけど
```
username: <%= ENV["POSTGRES_USER"] %>
password: <%= ENV["POSTGRESS_PASSWORD"] %>
```
なので環境変数どこで設定しているのか見つからないです。

**Comment by eiel** [comment]
本番の？

**Comment by eiel** [comment]
https://github.com/parkmap-h/parkmap/blob/master/Dockerfile

**Comment by eiel** [comment]
特に指定しない場合は、

ユーザ名 ログインユーザ
パスワード 必要なし

dockerの場合は上記がデフォルト

**Comment by k2works** [comment]
了解です、つながりました。
RubyMineのデーターベースエクスプローラーから操作できるようにしたかったもんで。
