### ISSUE TITLE
ロードマップを考える

### ISSUE THREAD

**Issue by eiel** [parkmap-h/parkmap#60]
せっかくなので、真面目に先のことを考えてみるのもよいかもしれない。

真面目にヒロハタへの参加を考えてみる。

# マイルストーン
## 大きいマイルストーン
* 2015年7月 ヒロハタ公開発表会
* 2016年3月 ヒロハタ公開発表会

## 小さいマイルストーン

* 毎月行なわれるヒロハタ

# 詳細
##  2015年7月 ヒロハタ公開発表会

* MVPの達成
  * 安い駐車場が見つけられる

## 2016年3月 ヒロハタ公開発表会

* 完成度の向上
  * リテラシーが低い人でも利用できる、参加できる

## 毎月行なわれるヒロハタ 

* 最低限達成するタスクの決定と達成
* タスク意外の作業環境の改善
* 巻き込みしやすくする工夫を一つ

**Comment by k2works** [comment]
小さいマイルストン＝ストーリー
大きいマイルストン＝いくつかのストーリー
ぐらいの粒度？

**Comment by eiel** [comment]
大きいマイルストーンは3月,4月,5月,6月のマイルストーンを含むと言えるので含有関係ですね。

ストーリーを1ヶ月でできる範囲に分割しなおさないとイコールで結べないかな。

**Comment by eiel** [comment]
大きいマイルストーン =  いくつかのGitHubのマイルストーン
小さなマイルストーン = GitHubのマイルストーン
GitHubのマイルストーン = 1つ以上のストーリー

とかぐらいだとはまりそうではある。

**Comment by k2works** [comment]
大きいマイルストーンはTrelloで管理するというのはどうよ？
https://trello.com/b/xhZks1lL/-
WIPが2015年7月ヒロハタ公開発表会の内容です。
ちなみにGitHubでマイルストーンを新規登録するとTrelloのStoryに連動して作ってくれます。
ただし、同期はとってくれません。

**Comment by k2works** [comment]
マイルストーンをストーリー単位からヒロハタレギュラーミーティング単位に変更。
https://github.com/parkmap-h/parkmap/milestones
合わせてロードマップにリストを追加
https://trello.com/b/xhZks1lL/-

**Comment by k2works** [comment]
ステータスの定義を少し変えました。
Done・・・完了したストーリー・フィーチャー・タスク
Working・・・仕掛りのストーリー・フィーチャー・タスク
Ready・・・現在のマイルストーン内のストーリー・フィーチャー・タスク
Backlog・・・それ以外

**Comment by k2works** [comment]
https://trello.com/b/xhZks1lL/-
とりあえず、Trelloでのロードマップ管理を私が担当します。
