### ISSUE TITLE
ランディングページの作成

### ISSUE THREAD

**Issue by eiel** [parkmap-h/parkmap#86]

**Comment by k2works** [comment]
これも2015年7月 ヒロハタ公開発表会にリリースするやつ？

**Comment by eiel** [comment]
時間がかかるものでもないしさっさとつくるほうがいいと思う。

**Comment by eiel** [comment]
なので、3月に設定してある。

**Comment by k2works** [comment]
ほい、GitHubページでやるの？

**Comment by eiel** [comment]
index.htmlを移動して、index.htmlをランディングページでいいんじゃないかなぁ。ドメインとるか悩ましい。

**Comment by k2works** [comment]
ランディングページ関連をストーリーにまとめました。
https://github.com/parkmap-h/parkmap/issues/92
